- hosts: aws
  tasks:
    - name: Set Facts
      set_fact:
        repo: "{{ lookup('env', 'DOCKER_REPOSITORY') }}"
        tag: "{{ lookup('env', 'IMAGE_TAG') }}"

    - name: Pull Docker container
      shell: docker pull {{ repo }}/ws:{{ tag }}
      register: output

    - name: Debug the output
      debug:
        var: output
