- hosts: localhost
  connection: local
  tasks:
    - name: restart a particular instance by its ID
      amazon.aws.ec2_instance:
        state: running
        instance_ids:
          - i-006852abccae49b60
        region: us-east-1
        access_key: "{{ lookup('env', 'AWS_SECRET') }}"