- name: Start instance by its ID and log public IP
  hosts: localhost
  tasks:
  - name: Start instance by its ID
    amazon.aws.ec2_instance:
      instance_ids: "{{ lookup('env', 'INSTANCE_IDS') }}"
      region: us-east-1
      state: running
    register: output

  - name: Debug the output
    debug:
      var: output

  - name: Extract public IP
    set_fact:
      instance_id: "{{ output.instances[0].public_ip_address }}"

  - name: Debug the instance ID
    debug:
      var: instance_id
