- hosts: win
  tasks:
    - name: Set build configuration
      set_fact:
        build_configuration: "{{ lookup('env', 'BUILD_CONFIGURATION') }}"
      when: build_configuration is not defined

    - name: Build .NET project
      win_shell: dotnet build QuantConnect.Lean.Launcher.csproj --configuration "{{ build_configuration }}"
      args:
        chdir: C:\repos\quantconnect\Lean\Launcher
      register: build_output
    
    - name: Debug the build output
      debug:
        var: build_output
