- hosts: win
  gather_facts: false
  
  tasks:
    - name: Build .NET project
      win_shell: dotnet build QuantConnect.Lean.Launcher.csproj --configuration {{ lookup('env', 'BUILD_CONFIGURATION') }}
      args:
        chdir: C:\repos\quantconnect\Lean\Launcher
      register: build_output
    
    - name: Debug the build output
      debug:
        var: build_output
