- hosts: win
  tasks:
    - name: Set build configuration
      set_fact:
        container_tag: "{{ lookup('env', 'CONTAINER_TAG') }}"
      when: container_tag is not defined

    - name: Build Docker container
      win_shell: docker buildx build --no-cache -t sebastianluen/amm:{{ container_tag }} .
      args:
        chdir: C:\repos\quantconnect\Lean
      register: build_output
    
    - name: Debug the build output
      debug:
        var: build_output
