- hosts: win
  gather_facts: false
  
  tasks:
    - name: Set Facts
      set_fact:
        repo: "{{ lookup('env', 'DOCKER_REPOSITORY') }}"
        tag: "{{ lookup('env', 'IMAGE_TAG') }}"

    - name: Build Docker container
      win_shell: docker buildx build -f ./repos/trade/src/connector/api_minlp/DockerfileWs -t {{ repo }}/ws:{{ tag }} .
      args:
        chdir: C:\
      register: output
    
    - name: Log output
      debug:
        var: output
