- hosts: win
  tasks:
    - name: Build Docker container
      win_shell: docker tag sebastianluen/amm:{{ lookup('env', 'SRC_TAG') }} sebastianluen/amm:{{ lookup('env', 'TGT_TAG') }}
      register: output
    
    - name: Debug the output
      debug:
        var: output
