- hosts: win
  tasks:
    - name: Build Docker container
      docker_image:
        name: docker.io/sebastianluen/ws
        tag: prod
        push: yes
        source: local
    
    - name: Debug the output
      debug:
        var: output
