- hosts: win
  tasks:
    - name: Build Docker container
      win_shell: docker push sebastianluen/ws:{{ tgt_tag }}
      register: output
    
    - name: Debug the output
      debug:
        var: output
