- hosts: win
  tasks:
    - name: Push Docker container
      ansible.windows.win_command:
        cmd: docker login -u {{ lookup('env', 'DOCKER_USER') }} -p {{ lookup('env', 'DOCKER_PASSWORD') }} https://docker.io & docker push sebastianluen/ws:prod
